<h1 style="font-size: 30px; font-weight: bold; text-align: center;">
  ASSIGNMENT-3
</h1>

**Q1-**

In [67]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


data = pd.read_csv("USA_Housing.csv")

print(data.head())
print(data.columns)

   Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0       79545.45857             5.682861                   7.009188   
1       79248.64245             6.002900                   6.730821   
2       61287.06718             5.865890                   8.512727   
3       63345.24005             7.188236                   5.586729   
4       59982.19723             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  
0                          4.09      23086.80050  1.059034e+06  
1                          3.09      40173.07217  1.505891e+06  
2                          5.13      36882.15940  1.058988e+06  
3                          3.26      34310.24283  1.260617e+06  
4                          4.23      26354.10947  6.309435e+05  
Index(['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price'],
      dtype='object')


(A)  
Divide the dataset into input features (all columns except price) and output variable  
(price)  

In [68]:
X = data.drop(columns=['Price']).values
y = data['Price'].values

print("Columns in dataset:", data.columns.tolist())
print("Shape of X (features):", X.shape)
print("Shape of y (target):", y.shape)

print("\nFirst 5 rows of X:\n", X[:5])
print("\nFirst 5 values of y:\n", y[:5])

Columns in dataset: ['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms', 'Avg. Area Number of Bedrooms', 'Area Population', 'Price']
Shape of X (features): (5000, 5)
Shape of y (target): (5000,)

First 5 rows of X:
 [[7.95454586e+04 5.68286132e+00 7.00918814e+00 4.09000000e+00
  2.30868005e+04]
 [7.92486424e+04 6.00289981e+00 6.73082102e+00 3.09000000e+00
  4.01730722e+04]
 [6.12870672e+04 5.86588984e+00 8.51272743e+00 5.13000000e+00
  3.68821594e+04]
 [6.33452401e+04 7.18823609e+00 5.58672866e+00 3.26000000e+00
  3.43102428e+04]
 [5.99821972e+04 5.04055452e+00 7.83938779e+00 4.23000000e+00
  2.63541095e+04]]

First 5 values of y:
 [1059033.558  1505890.915  1058987.988  1260616.807   630943.4893]


(B)            
Scale the values of input features.  

In [69]:

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Scaled feature sample (first 5 rows):\n", X_scaled[:5])


Scaled feature sample (first 5 rows):
 [[ 1.02865969 -0.29692705  0.02127433  0.08806222 -1.31759867]
 [ 1.00080775  0.02590164 -0.25550611 -0.72230146  0.40399945]
 [-0.68462915 -0.11230283  1.5162435   0.93084045  0.07240989]
 [-0.49149907  1.22157207 -1.39307717 -0.58453963 -0.18673422]
 [-0.80707253 -0.94483368  0.84674187  0.20151314 -0.98838741]]


(C)    
  Divide input and output features into five folds. 

In [70]:
indices = np.arange(len(X_scaled))
np.random.shuffle(indices)

folds = np.array_split(indices, 5)

for i, fold in enumerate(folds, 1):
    print(f"Fold {i}: {len(fold)} samples")


Fold 1: 1000 samples
Fold 2: 1000 samples
Fold 3: 1000 samples
Fold 4: 1000 samples
Fold 5: 1000 samples


(D)        
Run five iterations, in each iteration consider one-fold as test set and remaining 
four sets as training set. Find the beta (𝛽) matrix, predicted values, and R2_score 
for each iteration using least square error fit.

In [71]:

beta_list = []  
r2_s = []   

for i in range(5):
    test_idx = folds[i]
    X_test, y_test = X_scaled[test_idx], y[test_idx]
    train_idx = np.concatenate([folds[j] for j in range(5) if j!=i])
    X_train, y_train = X_scaled[train_idx], y[train_idx]

    X_train_bias = np.c_[np.ones(X_train.shape[0]), X_train]
    X_test_bias  = np.c_[np.ones(X_test.shape[0]), X_test]

    beta = np.linalg.inv(X_train_bias.T@X_train_bias)@(X_train_bias.T @ y_train)

    y_pred=X_test_bias @ beta
    score=r2_score(y_test, y_pred)

    beta_list.append(beta)
    r2_s.append(score)

    print(f"Iteration {i+1}")
    print("Beta coefficients:\n", beta)
    print("R2_score:", score, "\n")


Iteration 1
Beta coefficients:
 [1232295.41431078  229295.12169885  164774.17723437  121347.25062335
    2241.76878869  150950.28318239]
R2_score: 0.915624774854771 

Iteration 2
Beta coefficients:
 [1232039.87990824  229487.55387449  163335.50973855  121214.889636
    1362.87280849  150277.12327973]
R2_score: 0.9236454644383387 

Iteration 3
Beta coefficients:
 [1233373.28485355  229869.76935062  165108.61630722  122309.70562153
    1969.76228957  152068.11025107]
R2_score: 0.916609354085722 

Iteration 4
Beta coefficients:
 [1231315.59164667  230097.72334034  163930.10813771  120963.88451255
    2530.80066234  150536.3166272 ]
R2_score: 0.9153963244889614 

Iteration 5
Beta coefficients:
 [1231354.1912127   231011.79652308  163850.56819392  120939.73271902
    2091.86932031  150498.2983476 ]
R2_score: 0.917134125375134 



(E)          
Use the best value of (𝛽) matrix (for which R2_score is maximum), to train the 
regressor for 70% of data and test the performance for remaining 30% data

In [72]:
b_index = np.argmax(r2_s)
b_beta = beta_list[b_index]

print("\nb R2_score from cross-validation:", r2_s[b_index])
print("b Beta coefficients:\n", b_beta)

split = int(0.7 * len(X_scaled))
X_train, y_train = X_scaled[:split], y[:split]
X_test, y_test = X_scaled[split:], y[split:]

X_train_bias = np.c_[np.ones(X_train.shape[0]), X_train]
X_test_bias  = np.c_[np.ones(X_test.shape[0]), X_test]

final_beta = np.linalg.inv(X_train_bias.T @ X_train_bias) @ (X_train_bias.T @ y_train)

y_pred = X_test_bias @ final_beta

final_r2 = r2_score(y_test, y_pred)

print("\nFinal model evaluation on 30% test set")
print("Final Beta coefficients:\n", final_beta)
print("Final R2_score:", final_r2)



b R2_score from cross-validation: 0.9236454644383387
b Beta coefficients:
 [1232039.87990824  229487.55387449  163335.50973855  121214.889636
    1362.87280849  150277.12327973]

Final model evaluation on 30% test set
Final Beta coefficients:
 [1233516.27706963  231026.50499134  164126.40645338  121120.90089886
    1310.72742428  150279.13642153]
Final R2_score: 0.9176499755975894


**Q2-**           
Concept of Validation set for Multiple Linear Regression (Gradient Descent  
Optimization)  
Consider the same dataset of Q1, rather than dividing the dataset into five folds, divide the 
dataset into training set (56%), validation set (14%), and test set (30%).  
Consider four different values of learning rate i.e. {0.001,0.01,0.1,1}. Compute the values of 
regression coefficients for each value of learning rate after 1000 iterations.  
For each set of regression coefficients, compute R2_score for validation and test set and find 
the best value of regression coefficients.

In [73]:
data = pd.read_csv("USA_Housing.csv")

X = data.drop(columns=['Price']).values
y = data['Price'].values

X = StandardScaler().fit_transform(X)

X = np.c_[np.ones(X.shape[0]), X]

n = len(X)
train_end = int(0.56 * n)
val_end   = int(0.70 * n)

X_train, y_train = X[:train_end], y[:train_end]
X_val, y_val     = X[train_end:val_end], y[train_end:val_end]
X_test, y_test   = X[val_end:], y[val_end:]

def gradient_descent(X, y, lr, iters=1000):
    m, n = X.shape
    beta = np.zeros(n)
    for _ in range(iters):
        beta -= (lr/m) * (X.T @ (X @ beta - y))
    return beta

learning_rates = [0.001, 0.01, 0.1, 1]
best_beta, best_lr, best_val_r2, best_test_r2 = None, None, -1, None

for lr in learning_rates:
    beta = gradient_descent(X_train, y_train, lr, iters=1000)

    val_r2  = r2_score(y_val,  X_val @ beta)
    test_r2 = r2_score(y_test, X_test @ beta)

    print(f"LR={lr}\n  Validation R2={val_r2:.4f}\n    Test R2={test_r2:.4f}")

    if val_r2 > best_val_r2:
        best_beta, best_lr, best_val_r2, best_test_r2 = beta, lr, val_r2, test_r2

# Final best results
print("\nBest Learning Rate:    \n  ", best_lr)
print("Best Validation R2:  \n  ", best_val_r2)
print("Corresponding Test R2:   \n  ", best_test_r2)
print("Best Beta coefficients:  \n  ", best_beta)


LR=0.001
  Validation R2=-0.9353
    Test R2=-0.8082
LR=0.01
  Validation R2=0.9151
    Test R2=0.9175
LR=0.1
  Validation R2=0.9151
    Test R2=0.9175
LR=1
  Validation R2=0.9151
    Test R2=0.9175

Best Learning Rate:    
   0.1
Best Validation R2:  
   0.9151040123364315
Corresponding Test R2:   
   0.917477081644098
Best Beta coefficients:  
   [ 1.23244775e+06  2.31682635e+05  1.63635272e+05  1.19025219e+05
 -2.74956842e+02  1.50705906e+05]


**Q3-**      
1. Load the dataset with following column names ["symboling", "normalized_losses",  
"make", "fuel_type", "aspiration","num_doors", "body_style", "drive_wheels",  
"engine_location", "wheel_base", "length", "width", "height", "curb_weight",  
"engine_type", "num_cylinders", "engine_size", "fuel_system", "bore", "stroke",  
"compression_ratio", "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"]  
and replace all ? values with NaN  

 


In [74]:
import pandas as pd
import numpy as np

cols = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration",
        "num_doors", "body_style", "drive_wheels", "engine_location", "wheel_base",
        "length", "width", "height", "curb_weight", "engine_type", "num_cylinders",
        "engine_size", "fuel_system", "bore", "stroke", "compression_ratio",
        "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"]

data = pd.read_csv("imports-85.data.csv", names=cols)

data.replace("?", np.nan, inplace=True)

print("Dataset shape:", data.shape)
print(data.head())


Dataset shape: (205, 26)
   symboling normalized_losses         make fuel_type aspiration num_doors  \
0          3               NaN  alfa-romero       gas        std       two   
1          3               NaN  alfa-romero       gas        std       two   
2          1               NaN  alfa-romero       gas        std       two   
3          2               164         audi       gas        std      four   
4          2               164         audi       gas        std      four   

    body_style drive_wheels engine_location  wheel_base  ...  engine_size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel_system  bore  stroke compression_ra

2       
 Replace all NaN values with central tendency imputation. Drop the rows with NaN  
values in price column  

In [75]:
numeric_cols = ["symboling", "normalized_losses", "wheel_base", "length", "width", 
                "height", "curb_weight", "engine_size", "bore", "stroke",
                "compression_ratio", "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"]

for col in numeric_cols:
    data[col] = pd.to_numeric(data[col], errors="coerce")

for col in numeric_cols:
    data[col].fillna(data[col].mean(), inplace=True)

categorical_cols = list(set(cols) - set(numeric_cols))
for col in categorical_cols:
    data[col].fillna(data[col].mode()[0], inplace=True)

data = data.dropna(subset=["price"])

print("Remaining rows after cleaning:", data.shape)


Remaining rows after cleaning: (205, 26)


C:\Users\jayas\AppData\Local\Temp\ipykernel_6788\3652963809.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mean(), inplace=True)
C:\Users\jayas\AppData\Local\Temp\ipykernel_6788\3652963809.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For exam

3          
 There are 10 columns in the dataset with non-numeric values. Convert these values to  
numeric values using following scheme:  
(i) For “num_doors” and “num_cylinders”: convert words (number names) to figures  
for e.g., two to 2  
(ii) For "body_style", "drive_wheels": use dummy encoding scheme  
(iii) For “make”, “aspiration”, “engine_location”,fuel_type: use label encoding  
scheme  
(iv) For fuel_system: replace values containing string pfi to 1 else all values to 0.  
(v) For engine_type: replace values containing string ohc to 1 else all values to 0.  

In [76]:

num_map = {
    "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "eight": 8, "twelve": 12
}
data["num_doors"] = data["num_doors"].replace(num_map).astype(int)
data["num_cylinders"] = data["num_cylinders"].replace(num_map).astype(int)

data = pd.get_dummies(data, columns=["body_style", "drive_wheels"], drop_first=True)

label_enc_cols = ["make", "aspiration", "engine_location", "fuel_type"]
le = LabelEncoder()
for col in label_enc_cols:
    data[col] = le.fit_transform(data[col])

data["fuel_system"] = data["fuel_system"].apply(lambda x: 1 if "pfi" in x else 0)
data["engine_type"] = data["engine_type"].apply(lambda x: 1 if "ohc" in x else 0)

print("Dataset after encoding:\n", data.head())


Dataset after encoding:
    symboling  normalized_losses  make  fuel_type  aspiration  num_doors  \
0          3              122.0     0          1           0          2   
1          3              122.0     0          1           0          2   
2          1              122.0     0          1           0          2   
3          2              164.0     1          1           0          4   
4          2              164.0     1          1           0          4   

   engine_location  wheel_base  length  width  ...  peak_rpm  city_mpg  \
0                0        88.6   168.8   64.1  ...    5000.0        21   
1                0        88.6   168.8   64.1  ...    5000.0        21   
2                0        94.5   171.2   65.5  ...    5000.0        19   
3                0        99.8   176.6   66.2  ...    5500.0        24   
4                0        99.4   176.6   66.4  ...    5500.0        18   

   highway_mpg    price  body_style_hardtop  body_style_hatchback  \
0         

C:\Users\jayas\AppData\Local\Temp\ipykernel_6788\3998969858.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["num_doors"] = data["num_doors"].replace(num_map).astype(int)
C:\Users\jayas\AppData\Local\Temp\ipykernel_6788\3998969858.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["num_cylinders"] = data["num_cylinders"].replace(num_map).astype(int)



4    
Divide the dataset into input features (all columns except price) and output variable  
(price). Scale all input features.

In [77]:
X = data.drop(columns=["price"]).values
y = data["price"].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("X shape:", X_scaled.shape, "y shape:", y.shape)


X shape: (205, 29) y shape: (205,)


  
5          
 Train a linear regressor on 70% of data (using inbuilt linear regression function of  
Python) and test its performance on remaining 30% of data. 

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

print("Linear Regression R2 score:", r2_score(y_test, y_pred))


Linear Regression R2 score: 0.8044422435762588
